# Generated by Django 5.2.8 on 2025-11-26 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("venue_id", models.AutoField(primary_key=True, serialize=False)),
                ("venue_name", models.CharField(max_length=255)),
                ("floor_area", models.PositiveIntegerField()),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("Conference", "Conference"),
                            ("Hall", "Hall"),
                            ("Auditorium", "Auditorium"),
                            ("Study Room", "Study Room"),
                        ],
                        max_length=50,
                    ),
                ),
                ("venue_capacity", models.PositiveIntegerField()),
                ("floor", models.CharField(max_length=50)),
                (
                    "under_renovation",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")], default="N", max_length=1
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venues",
                        to="accounts.agentprofile",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venues",
                        to="accounts.building",
                    ),
                ),
            ],
        ),
    ]
