# Generated by Django 5.2.8 on 2025-11-22 10:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='agent_name',
            field=models.CharField(default='AnAgent', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='contact_number',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customer_name',
            field=models.CharField(default='ACustomer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_assignement',
            field=models.TextField(default='NeedTeam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.team'),
        ),
    ]
