# Generated by Django 5.2.8 on 2025-11-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agentprofile_agent_name_agentprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='email',
            field=models.EmailField(default='add email', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='username',
            field=models.CharField(default='addUsername', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(default='addEmail', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='username',
            field=models.CharField(default='AddUsername', max_length=100),
            preserve_default=False,
        ),
    ]
