# Generated by Django 5.2.8 on 2025-11-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_venue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'permissions': [('can_add_venue', 'Can add venue')]},
        ),
    ]
