# Generated by Django 5.2.8 on 2025-11-29 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.RESTRICT, to='accounts.customerprofile'),
            preserve_default=False,
        ),
    ]
