# Generated by Django 5.2.8 on 2025-11-29 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(default='Unknown Building', max_length=255)),
                ('district', models.CharField(default='Unknown District', max_length=255)),
                ('street', models.CharField(default='Unknown Street', max_length=255)),
                ('city', models.CharField(default='Unknown City', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255)),
                ('building_floor', models.IntegerField(default=1)),
                ('venue_type', models.CharField(choices=[('Conference', 'Conference'), ('Hall', 'Hall'), ('Auditorium', 'Auditorium'), ('Study Room', 'Study Room')], max_length=50)),
                ('venue_capacity', models.PositiveIntegerField(default=1)),
                ('venue_floor_area', models.PositiveIntegerField(default=1)),
                ('under_renovation', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='venues', to='accounts.agentprofile')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='venues', to='venues.building')),
            ],
        ),
        migrations.CreateModel(
            name='AmenityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.amenity')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venue')),
            ],
            options={
                'unique_together': {('amenity', 'venue')},
            },
        ),
    ]
