# Generated by Django 5.2.8 on 2025-11-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amenityassignment',
            unique_together={('amenity', 'venue')},
        ),
        migrations.AddField(
            model_name='amenityassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='amenityassignment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='amenityassignment',
            name='pk',
        ),
    ]
