# Generated by Django 5.2.8 on 2025-11-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0002_remove_building_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="district",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
