# Generated by Django 5.2.8 on 2025-11-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_building_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="district",
            field=models.CharField(max_length=255),
        ),
    ]
